import { type Decision } from "@/domain/types";

export const sampleDecision: Decision = {
  id: "decision-apartment-1",
  title: "Sell or keep apartment",
  description:
    "Evaluate selling now versus keeping the apartment with value, risk, and flexibility in view.",
  alternatives: [
    { id: "sell-now", name: "Sell now" },
    { id: "keep-live", name: "Keep and live in it" },
    { id: "keep-rent", name: "Keep and rent it out" },
  ],
  categories: [
    { id: "wealth", name: "Wealth", weight: 0.25 },
    { id: "liquidity", name: "Liquidity", weight: 0.2 },
    { id: "housing-security", name: "Housing Security", weight: 0.25 },
    { id: "stress", name: "Stress", weight: 0.15 },
    { id: "family", name: "Family Obligations", weight: 0.15 },
  ],
  factors: [
    {
      id: "f1",
      alternativeId: "sell-now",
      categoryId: "liquidity",
      description: "Immediate access to sale proceeds.",
      direction: "pro",
      gravity: 4,
      probability: 0.95,
      evidenceConfidence: "strong",
    },
    {
      id: "f2",
      alternativeId: "sell-now",
      categoryId: "family",
      description: "Can repay family debt quickly.",
      direction: "pro",
      gravity: 4,
      probability: 0.9,
      evidenceConfidence: "strong",
      constraintType: "must_have",
    },
    {
      id: "f3",
      alternativeId: "sell-now",
      categoryId: "housing-security",
      description: "Need to rent before next purchase.",
      direction: "con",
      gravity: 4,
      probability: 0.7,
      evidenceConfidence: "some",
    },
    {
      id: "f4",
      alternativeId: "keep-live",
      categoryId: "housing-security",
      description: "Immediate housing stability.",
      direction: "pro",
      gravity: 5,
      probability: 0.95,
      evidenceConfidence: "strong",
    },
    {
      id: "f5",
      alternativeId: "keep-live",
      categoryId: "liquidity",
      description: "Capital remains tied up in property.",
      direction: "con",
      gravity: 4,
      probability: 0.9,
      evidenceConfidence: "strong",
    },
    {
      id: "f6",
      alternativeId: "keep-rent",
      categoryId: "wealth",
      description: "Could keep upside while adding rental income.",
      direction: "pro",
      gravity: 3,
      probability: 0.65,
      evidenceConfidence: "some",
    },
    {
      id: "f7",
      alternativeId: "keep-rent",
      categoryId: "stress",
      description: "Tenant management and vacancy risk.",
      direction: "con",
      gravity: 3,
      probability: 0.55,
      evidenceConfidence: "some",
    },
  ],
  constraints: [
    {
      id: "c1",
      description: "Repay family on a clear timeline.",
      type: "must_have",
      appliesToAlternativeIds: ["sell-now", "keep-live", "keep-rent"],
      satisfied: true,
    },
  ],
  riskPreference: "balanced",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
